baseURL = "http://avi.im/blag"
languageCode = "en-us"
title = "blag"
theme = "skyfall"

[permalinks]
  posts = "/:year/:slug/"

[markup.goldmark.renderer]
unsafe= true

[params]
  githubUsername = "avinassh"
  goatSiteName = "avi"

[menu]
  [[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about"

  [[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "/projects"
