baseURL = "https://avi.im/blag"
languageCode = "en-us"
title = "blag"
theme = "skyfall"

[permalinks]
  posts = "/:year/:slug/"

[markup.goldmark.renderer]
  unsafe = true

[params]
  githubUsername = "avinassh"
  goatSiteName = "avi"
  rcscout = "a4aabd5087bb19daf083302de1b46650"

[menu]
  [[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about"

  [[menu.main]]
  identifier = "now"
  name = "Now"
  url = "/now"

#  [[menu.main]]
#  identifier = "resume"
#  name = "Resume"
#  url = "https://avi.im/resume.pdf"
#
#  [[menu.main]]
#  identifier = "projects"
#  name = "Projects"
#  url = "/projects"
#
#  [[menu.main]]
#  identifier = "subscribe"
#  name = "Subscribe"
#  url = "https://tinyletter.com/avi-im"