name: build-deploy-hugo

on: [push, pull_request, workflow_dispatch]
#  push:
#    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: install hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: clean up
        run: |
          if [ -d "public" ]; then
            rm -rf public
          fi

      - name: setup
        run: |
          git worktree add public gh-pages

      - name: build
        run: hugo --minify

      - name: commit
        run: |
          cd public
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add --all
          git commit -am "deployed: '$(git log -1 --pretty=%B)'"
     
      - name: deploy
        run: git push --all
